### ISSUE TITLE
return value of host function from archspec.cpu should include regular strings, not unicode strings (in Python 2)

### ISSUE THREAD

**Issue by boegel** [archspec/archspec#13]
```
>>> from archspec.cpu import host
>>> host_info = host()
>>> host_info.name
u'skylake'
```

@alalazo Do we have a good reason to use unicode string values?
It can be painful to deal with a mix of regular string values and unicode values (only relevant in Python 2), see https://github.com/easybuilders/easybuild-framework/issues/3284.

**Comment by alalazo** [comment]
That's because we load values from JSON and avoid to have something like [this](https://stackoverflow.com/questions/956867/how-to-get-string-objects-instead-of-unicode-from-json/13105359#13105359) in archspec to load a string from JSON files if using Python 2.X. Since Python 2.X is officially unsupported (and I secretly hope that our projects would move someday to Python 3.X only support) I'd avoid complicating our codebase for only this purpose.

**Comment by boegel** [comment]
It wouldn't be very complicated, just a well aimed `str(...)` I think, but I support your view on not taking special measures for the sake of better supporting a dead language like Python 2 (and perhaps that way encouraging people to keep using it).
