### ISSUE TITLE
wrong arch name for skylake_avx512 node with missing instruction

### ISSUE THREAD

**Issue by smoors** [archspec/archspec#72]
the missing instruction is `aes`

```
$ python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import archspec
>>> archspec.__version__
'0.1.3'
>>> import archspec.cpu
>>> archspec.cpu.host().name
'x86_64_v4'

$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                36
On-line CPU(s) list:   0-35
Thread(s) per core:    1
Core(s) per socket:    18
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
Stepping:              4
CPU MHz:               2300.000
BogoMIPS:              4600.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              25344K
NUMA node0 CPU(s):     0-17
NUMA node1 CPU(s):     18-35
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear spec_ctrl intel_stibp flush_l1d
```

**Comment by alalazo** [comment]
Hi @smoors and thanks for the report. Since `archspec` is about binary compatibility, I think the library is currently correct. From GCC man page, optimizing for `skylake_avx512` means that the compiler can emit:
```
skylake-avx512
               Intel Skylake Server CPU with 64-bit extensions, MOVBE, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, POPCNT, PKU, AVX, AVX2, AES, PCLMUL,
               FSGSBASE, RDRND, FMA, BMI, BMI2, F16C, RDSEED, ADCX, PREFETCHW, CLFLUSHOPT, XSAVEC, XSAVES, AVX512F, CLWB, AVX512VL, AVX512BW, AVX512DQ and
               AVX512CD instruction set support.
```
Among the instructions there is also AES, so if we remove that it means we might get `skylake_avx512` binaries that are incompatible with machines detected as `skylake_avx512` (i.e. you might have AES instructions in the binary and get an illegal intruction error when you run it on the host posted in the description).

Do you have more details as of why AES is missing? I'm asking that because we have similar reports for other kind of architectures, e.g. https://github.com/archspec/archspec-json/issues/38, so we are considering if it is worth relaxing the strict adherence to the naming that compilers use. We'd like to investigate better each use case because that doesn't only involve removing e.g. the `aes` flag, but also tweaking compiler optimization flags to explicitly avoid emitting AES instructions (`-mno-aes` on GCC).

**Comment by stevenvdb** [comment]
We have a few Intel(R) Xeon(R) Gold 6140 processors at our site which all support some avx-512 instructions. One of the machines has microcode version `0x200005e` and compared to the others (`0x200003a` and `0x2006a0a`), the one with microcode `0x200005e`  does not show `aes` under Flags when running `lscpu`. I tried to run a program that includes `aes` instructions, and on the machine with microcode `0x200005e`  it gives `Illegal instruction` errors. I have no clue why this is the case.

**Comment by alalazo** [comment]
@stevenvdb It _may_ be the case that `aes` is configurable from BIOS, see [here](https://techlibrary.hpe.com/docs/iss/proliant-gen10-uefi/GUID-D7147C7F-2016-0901-0A72-000000000BD4.html)

**Comment by stevenvdb** [comment]
> @stevenvdb It _may_ be the case that `aes` is configurable from BIOS, see [here](https://techlibrary.hpe.com/docs/iss/proliant-gen10-uefi/GUID-D7147C7F-2016-0901-0A72-000000000BD4.html)

You are right. After enabling it in the BIOS, archspec is working as expected.
